### ISSUE TITLE
Does not support detached labels

### ISSUE THREAD

**Issue by pbvarga1** [planetarypy/planetaryimage#11]
I tried opening the following Cassini image that has a detached label but it exploded:

http://pds-imaging.jpl.nasa.gov/data/cassini/cassini_orbiter/coiss_2090/data/1782761458_1782849980/W1782844276_1.LBL
http://pds-imaging.jpl.nasa.gov/data/cassini/cassini_orbiter/coiss_2090/data/1782761458_1782849980/W1782844276_1.IMG

```python
from planetaryimage import PDS3Image
image = PDS3Image.open('W1782844276_1.LBL')
```

Here is the error I got

```
/home/pbvarga1/Workspace/planetaryimage/planetaryimage/pds3image.py in start_byte(self)
     69                     % pointer.units)
     70         else:
---> 71             raise ValueError('Unsupported image pointer type')
     72 
     73     @property

ValueError: Unsupported image pointer type
```

There may be other reasons this image doesn't open.

**Comment by godber** [comment]
Fixed in https://github.com/planetarypy/planetaryimage/pull/12
