### ISSUE TITLE
Image should accept a URL and open it

### ISSUE THREAD

**Issue by godber** [planetarypy/planetaryimage#14]
Anyone have a good idea on what syntax we should add to allow users to open a file from a URL?  Should we offer a separate class method for it?  Inspect `stream` and see if its a URL then treat it as such?  Do we then download the image into a cache (probably)?

**Comment by wtolson** [comment]
I like the idea but this seems out of the scope of planetaryimage for me. An image catalog/manager/downloader seems like a separate tool that would exist in the planetarypy ecosystem.

**Comment by godber** [comment]
I agree with the need for a catalog module that would do sophisticated data access.  I also share you're reluctance to adding unnecessary features to planetaryimage, but the convenience of doing so may outweigh the extravagance (and complexity introduced).  I will let this ticket sit a bit and see how I feel later.  I think I am inclined to agree with you if we aggressively cross-referenced documentation with this catalog/data manager.

**Comment by godber** [comment]
Gonna just close this for now.
