### ISSUE TITLE
Tox and travis tests - make test

### ISSUE THREAD

**Issue by godber** [planetarypy/planetaryimage#32]
So, in a feature branch, I've just made some changes to the `test` target in the `Makefile` and it has occurred to me that the `tox.ini` and the `travis.yml` issue explicit `py.test tests` commands rather than running `make test`.  Is there some reason we shouldn't use `make test` in those places?

CC: @wtolson

**Comment by wtolson** [comment]
Not actually sure if it will break anything. I was mainly following the example of https://github.com/audreyr/cookiecutter-pypackage

**Comment by godber** [comment]
Thanks for the response!

Basically, I am trying to make sure that doctests in the source get tested when we run `make test` so I have changed the target to this:

```
py.test --doctest-modules --ignore=setup.py
```

Then I realized that tox and travis would still run the old version.  I will ponder this a bit, I need to fiddle with the `planetary_test_data` package a bit now.

**Comment by godber** [comment]
I have just duplicated the `py.test` command in all three places.
