### ISSUE TITLE
test_mission_data fails in Python 3

### ISSUE THREAD

**Issue by godber** [planetarypy/planetaryimage#35]
Fix this issue: https://travis-ci.org/planetarypy/planetaryimage/jobs/70781416

While doing so, extend the label tests to be more generic and test a few more label values for the core data products.

**Comment by pbvarga1** [comment]
The test should only test core products right?

**Comment by pbvarga1** [comment]
My test passes for ``make test-all`` but I think this pull request needs to be accepted https://github.com/planetarypy/planetary_test_data/pull/9 first for the test to pass Travis CI.

**Comment by pbvarga1** [comment]
So Ill send a pull request one that is accepted

**Comment by pbvarga1** [comment]
This was resolved by the changes to the test in https://github.com/planetarypy/planetaryimage/pull/37/files
