### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by wtolson** [planetarypy/planetaryimage#5]
Looks like you currently have MIT licence for this repo. It would be advantageous to have one licence for all the planetarypy projects. We should update this to BSD or change pvl to MIT. I'm fine with either.

We should also get a cookiecutter package together for planetarypy. I can put that together if you'd like.

**Comment by godber** [comment]
Great suggestion, please do!  @NikhilKalige FYI !!!

**Comment by wtolson** [comment]
Cookiecutter setup here: https://github.com/planetarypy/cookiecutter-pypackage. Feedback appreciated!

**Comment by godber** [comment]
Looks good enough to get started, but we should make a point to remember changes we'd benefit from making.

**Comment by godber** [comment]
@nikhilkalige, go ahead and use this.

**Comment by godber** [comment]
Thanks +wtolson
