### ISSUE TITLE
Change .travisci.yml to run the tox tests instead

### ISSUE THREAD

**Issue by godber** [planetarypy/planetaryimage#68]
It's always annoyed me that we use tox to run tests against multiple pythons and then in travis we redo this work and test multiple environments differently.  I think I have finally found an example that uses travis in conjunction with tox.  Check this out:

```
language: python
python:
 - 2.7
sudo: false
env:
 - TOX_ENV=py27
 - TOX_ENV=docs
 - TOX_ENV=lint
install:
 - pip install tox
 - pip install coveralls
script:
 - tox -e $TOX_ENV
after_success:
 - coveralls
```

Maybe it will work for us.

Example from RTFD: https://github.com/rtfd/readthedocs.org/blob/8ca4056da4bce471fa87e6e8a10f305c55f2fa53/.travis.yml

**Comment by wtolson** [comment]
I thought we did that at one point (https://github.com/planetarypy/planetaryimage/commit/29bc584e0a2fdcad9fe2e19ed922f55d3f3fd23f) but decided againt it as it had to then compile numpy and scipy leading to sloooow tests.

**Comment by godber** [comment]
Oh, good memory.  I should stop wanting to do this then.
