### ISSUE TITLE
Write some docs

### ISSUE THREAD

**Issue by godber** [planetarypy/planetaryimage#8]
We only have stubbed out docs, we should write something useful in `docs/` and in `README`.

**Comment by pbvarga1** [comment]
Just for clarification, do you want a doc for ``PDS3Image`` and ``CubeFile`` explaining what attributes the user can access? Or do you want me to go through viewing an image as well? I feel like viewing an image is covered in http://nbviewer.ipython.org/urls/gist.githubusercontent.com/godber/dfb5d012fda603619ab9/raw/b1db599f53a5c468075ff854e9056698bd005cc7/gistfile1.json so I don't think I should go through it again.

**Comment by godber** [comment]
I have a few thoughts on this .... first off, I think to some extent, we've gotten off on the wrong foot in one sense docs wise.  This is entirely my fault.  You ask "...explaining what attributes...", this is actually the role of docstrings.  A given function/method/classes options and arguments should be documented IN THE CODE in docstrings and in our case using the `numpydoc` extensions:

https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt

So, for this ticket, start with putting some sensible examples in here:

http://planetaryimage.readthedocs.org/en/latest/usage.html

You can pull them from the IPython notebook.  The docs at http://planetaryimage.readthedocs.org/en/latest/usage.html should stand alone.  It can have duplicate content from other places.

Keep in mind these docs have automatic generated PDF versions https://media.readthedocs.org/pdf/planetaryimage/latest/planetaryimage.pdf

If users download that they should get SOMETHING useful.

Then, when you get that done, lets take a crack at writing some proper docstrings.

**Comment by godber** [comment]
The thing that puzzles me here, is how do we convert IPython notebook type input into sensible documentation examples.  The notebook relies upon ".imshow()" to make its point most of the time.  That notebook could just be converted to restructured text I think using `nbconvert` and then embedded into the docs I guess.

**Comment by pbvarga1** [comment]
So the documentation shouldn't list the attributes available and just present examples?

**Comment by godber** [comment]
The documentation SHOULD include that, but you should not be writing it in the .rst files.  That information should be in the code (.py files) and sphinx should be configured to find and automatically include those docs.

**Comment by godber** [comment]
Completed in https://github.com/planetarypy/planetaryimage/pull/31
