### ISSUE TITLE
Collect sample data.

### ISSUE THREAD

**Issue by godber** [planetarypy/planetaryimage#9]
We need to collect a decent set of sample data to ensure that the library is robust.  I started this in my `gdal_pds` repo, it grabs some MER data, but its all very similar:

https://github.com/godber/gdal_pds/blob/master/get_test_data.py
https://github.com/godber/gdal_pds/blob/master/data.json

I'd really like to see data from every PDS Image Node mission represented.

**Comment by godber** [comment]
For each data product collected we should implement at the very least minimal "load" test.

I'd also like to point out the availability of AstroPy's `download_file` utility that includes caching:
http://docs.astropy.org/en/stable/utils/index.html#file-downloads

I don't want AstroPy as a required dependency for this package as a whole, but an optional dependency or a development dependency would be fine.

**Comment by godber** [comment]
This might be something we should make a call out to the community for ... aka twitter ...

**Comment by godber** [comment]
Start off by making a list of Missions that have image data on the PDS Imaging Node:

http://pds-imaging.jpl.nasa.gov/

Then add instruments to that list.  Note that a mission/spacecraft may have multiple imaging products.

Then add links to sample products to the instruments in that list.

Keep this list initially in a wiki page here or in a github checklist comment in the ticket.

**Comment by godber** [comment]
Some sample `pds2isis` commands that could be useful to convert from one filetype to another:

```
pds2isis from=pds3_1band.IMG to=1band_detached.cub+Tile+Lsb+Detached
pds2isis from=pds3_1band.IMG to=1band_detached.cub+Tile+Lsb+Attached
pds2isis from=pds3_1band.IMG to=1band_detached.cub+BandSequential+Lsb+Attached
pds2isis from=pds3_1band.IMG to=1band_detached.cub+BandSequential+Msb+Attached
pds2isis from=pds3_1band.IMG to=1band_detached.cub+UnsignedByte+0.0:0.0+BandSequential+Msb+Attached
```

**Comment by pbvarga1** [comment]
Should I test the images with only PDS3Imgage.open()? If not then what else should I test them with? Or should I not worry on if they work or not?

**Comment by godber** [comment]
Testing with `PDS3Image.open()` is the first step after generating the `data.json`.  So yeah.  Do you have the `data.json`?

**Comment by godber** [comment]
@pbvarga1 I am going to declare this task done, as other tasks will more fully satisfy the remaining requirements.  Mostly when you create a full `data.json` in the `planetary_test_data` package.
